- code/ecat_headers.json
- code/python/ecat.py
- code/python/ecat2nii.py
- code/python/read_ecat.py
- code/python/tests/test_thisbytes.py
Added 73 schemas and refactored schemas as well to make use of data type included in MAIN_HEADER, still untested on 6.3 or any 6.X ecats, but there isn't much that can done at this point now.
> Add 73 schemas

- code/python/ecat2nii.py
- code/python/tests/test_nifti_write.py
This makes the sif file, just like the matlab version. Note, the python ecat_read does no conversion on any values read in from an ecat. Thus the scaling in ecat2nii.py and ecat2nii.m are different to account for this fact w/ respect to frame start and delta times.
> Add sif file python

- .github/workflows/setup_and_cli_test_posix.yaml
- .gitignore
- Makefile
- pypet2bids/pypet2bids/dcm2niix4pet.py
- pypet2bids/pypet2bids/ecat_cli.py
- pypet2bids/pypet2bids/helper_functions.py
- pypet2bids/pyproject.toml
Added poetry 'build' command to Makefile to copy over metadata folder files to
a path that poetry/python packaging could resolve. Updated .gitignore to suit.
Renamed cli.py to ecat_cli.py since there is more than one cli floating around.
Added metadata copied from metadata/ folder project.toml for packaging
Moved key=value argparser object to helperfunctions as it's going to be used
everywhere in this project to accept user input metadata for PET.
> added cli for dcm2niix for PET

- matlab/Readme.md
- matlab/ecat2nii.m
- matlab/nii_tool.m
Previously ecat2nii.m required the image processing toolbox. This toolbox is often not purchased (it is not required by SPM). The modified code will use the image processing toolbox if it is installed, but fall back to the included [nii_tool](https://github.com/xiangruili/dicm2nii). 
There are two caveats:
1. I do not have the image processing toolbox, so I can not explicitly test my detection (e.g. I am not sure if `niftiwrite` is a built-in or .m file).
2. Personally, I would suggest removing the dependency on the image processing toolbox and only use nii_tool. This ensures consistent conversion for all users. Further, the developers should be aware that early versions of the IPP did not handle NIfTI correctly (e.g. dims set to 0). I would suggest using vetted open source code would be …
> Allow conversion without image processing toolbox

- metadata/PET_dicom_reconstruction_methods.json
Adding in a json file in metadata containing given ReconstructionMethod
input, along with the desired BIDS outputs that would result upon
collecting said input from a dicom file. This file will be used
in Matlab and Python for CI and testing.
> Added dicom recon method inputs and BIDS outputs

- pypet2bids/pypet2bids/dcm2niix4pet.py
- pypet2bids/pyproject.toml
added method to get TracerRadionuclide from dicom header and then
if gotten to write it out to the nifti sidecar.json
Can still be overridden w/ command line argument or by placing value
in spreadsheet.
> Added write out TracerRadionuclide from dicom to json

- pypet2bids/pypet2bids/dcm2niix4pet.py
Post dcm2niix method accepts either pandas dataframe as input or a structured dictionary, additionally added missing parentheses to .keys() in get_radionuclide()
> Added robustness to tsv data handling method, fixed small error w/ keys.()

- pypet2bids/pypet2bids/dcm2niix4pet.py
- pypet2bids/pypet2bids/helper_functions.py
- pypet2bids/pyproject.toml
Windows is bad, spaces are bad, this might need to escape/handle more than just that sort of nonsense. Currently just wraps quotes around paths passed to dcm2niix *if* they contain spaces. 
Need to test further on wacky windows paths.
> Sanitize bad paths

- .github/workflows/python.yaml
- pypet2bids/pypet2bids/dcm2niix4pet.py
- pypet2bids/pypet2bids/helper_functions.py
- pypet2bids/tests/test_helper_functions.py
- scripts/testphantoms
Updated dcm2niix4pet to parse BIDS entities from a nifti (or any) file is given as the destination argument.
`dcm2niix4pet sourcefolder -d /sub-01/ses-01/sub-01_ses-01_task-testtask_trc-C15_pet.nii.gz` will search the entire destination string, not just the parent folders for subject and session.
The output of the above command will be:
```
/sub-01/ses-01/sub-01_ses-01_task-testtask_trc-C15_pet.nii.gz
/sub-01/ses-01/sub-01_ses-01_task-testtask_trc-C15_pet.json
```
> Use full filename if given

- pypet2bids/pypet2bids/dcm2niix4pet.py
- pypet2bids/pypet2bids/helper_functions.py
- pypet2bids/pypet2bids/single_spreadsheet.py
- pypet2bids/pyproject.toml
- pypet2bids/tests/test_helper_functions.py
This PR adds functionality such that:
- If dcm2niix4pet is given the flag `--metadata-path` with no arguments it will search the image folder argument for a pet metadata spreadsheet and apply it
- If dcm2niix4pet is given the flag `--metadat-path` with a folder argument instead of "" or a file path, it will search the specified folder.
> Locate PET Spreadsheet in Imaging or Specified Folder

- pypet2bids/pypet2bids/dcm2niix4pet.py
Allows user to specify a tempdir base for situations where system temp folder is not appropriate (eg: small OS partition)
> Add dcm2niix4pet --tempdir <tempdir> option

- pypet2bids/pypet2bids/dcm2niix4pet.py
- pypet2bids/pyproject.toml
Allows user to specify a tempdir base for situations where system temp folder is not appropriate (eg: small OS partition)
> Add dcm2niix4pet --tempdir <tempdir> option (#211)

- pypet2bids/pyproject.toml
If I install pypet2bids in a fresh python 3.11 environment I get an error (see below) because pypet2bids depends on the obsolete python 3.11.1 version. I think it is safe to always use the latest 3.11 version, hence this PR
```console
py311: install_package_deps> python -I -m pip install 'pypet2bids>=1.0.12'
ERROR: Ignored the following versions that require a different python version: 0.0.10 Requires-Python >3.7.1,<3.10; 0.0.11 Requires-Python >3.7.1,<3.10; 0.0.12 Requires-Python >3.7.1,<3.10; 0.0.13 Requires-Python >3.7.1,<3.10; 0.0.14 Requires-Python >3.7.1,<3.10; 0.0.15 Requires-Python >3.7.1,<3.10; 0.0.4 Requires-Python >3.7.1,<3.10; 0.0.6 Requires-Python >3.7.1,<3.10; 0.0.7 Requires-Python >3.7.1,<3.10; 0.0.8 Requires-Python >3.7.1,<3.10; 0.0.9 Requires-Python >3.7.1,<3.10; 1.0.0 …
```
> Relax the very specific python 3.11.1 dependency to 3.11

- metadata/schema.json
- pypet2bids/poetry.lock
- pypet2bids/pypet2bids/dcm2niix4pet.py
- pypet2bids/pypet2bids/helper_functions.py
- pypet2bids/pyproject.toml
Pandas seems to consider booleans to be 1 and 0, this update uses the schema to check for 1 and 0 and if that entity should be a boolean converts it to  a python `True` or `False` which when written out as a json should persist as a bool type there.
> [ENH] Convert Boolean like Values to Python Type Bools

- pypet2bids/poetry.lock
- pypet2bids/pypet2bids/dcm2niix4pet.py
- pypet2bids/pypet2bids/helper_functions.py
- pypet2bids/pyproject.toml
all of these  checks and warnings need to be refactored to use the bids schema, but this at least silences much of it for use w/ 3rd party libraries and tools.
> silenced extra warnings, checking spreadsheet inputs too

- Makefile
- scripts/python_conversions.sh
Version v1.0.20220720 of dcm2niix fixed some issues with Phillips dicoms. Uncommented those previously failing phantoms in python_conversions.sh and ran `make phantoms` they convert and pass the validator.
> Tested previously failing phantoms, pass now.

- pypet2bids/pypet2bids/dcm2niix4pet.py
- pypet2bids/pyproject.toml
Issue: No json output after running `dcm2niix4pet`.
Reason: Older versions of `dcm2niix` don't generate the json sidecar by default.
Fix: Added `-b y` argument to `dcm2niix` to enable the generation of the json sidecar for older versions. This change should not affect the behavior with the latest version of `dcm2niix`.
> Bug fix: enable json sidecar generation for older dcm2niix versions

- README.md
- docs/installation.rst
- docs/usage.rst
- pypet2bids/pypet2bids/convert_pmod_to_blood.py
- pypet2bids/pypet2bids/helper_functions.py
- pypet2bids/pypet2bids/metadata_spreadsheet_example_reader.py
- pypet2bids/pypet2bids/multiple_spreadsheets.py
- pypet2bids/pypet2bids/read_ecat.py
- pypet2bids/pypet2bids/sidecar.py
- pypet2bids/pyproject.toml
closes issue #248 
----
📚 Documentation preview 📚: https://pet2bids--253.org.readthedocs.build/en/253/
> Updating Python Installation Instructions

- .github/workflows/phantoms.yaml
- .github/workflows/python.yaml
- matlab/updatejsonpetfile.m
- scripts/matlab_conversions.m
- scripts/python_conversions.sh
- scripts/testphantoms
----
📚 Documentation preview 📚: https://pet2bids--259.org.readthedocs.build/en/259/
> Switch phantoms to s3, update CI, fix bug with updatepetjson.m on GE dicoms

- pypet2bids/pypet2bids/dcm2niix4pet.py
- pypet2bids/pypet2bids/ecat.py
- pypet2bids/pypet2bids/ecat_cli.py
- pypet2bids/pypet2bids/helper_functions.py
- pypet2bids/pypet2bids/update_json_pet_file.py
- pypet2bids/pyproject.toml
- pypet2bids/tests/test_dcm2niix4pet.py
- pypet2bids/tests/test_ecat.py
- pypet2bids/tests/test_library_command_line_interfaces.py
Moving "generalize-able" methods out from more specified classes, updating ecat.py with lastest functionality in the process, and ultimately adding on CLI's.
CLI's will enable a user to input a pet json file and a dicom, spreadsheet, or ecat file to update the values within the supplied json.
Closes #255 
----
📚 Documentation preview 📚: https://pet2bids--262.org.readthedocs.build/en/262/
> Externalizing update PET json's

- matlab/ecat2nii.m
ecat validation remains unchanged by adding this statement
----
📚 Documentation preview 📚: https://pet2bids--271.org.readthedocs.build/en/271/
> add conditional statement

- pypet2bids/pypet2bids/dcm2niix4pet.py
- pypet2bids/pypet2bids/update_json_pet_file.py
- pypet2bids/pyproject.toml
fixes issue where extra/missing blood values read in from a spreadsheet would cause conversion to error out due to array/list/dataseries length mismatch. Determines the length of the longest blood column and appends zeros to all other columns that are too short.
----
📚 Documentation preview 📚: https://pet2bids--273.org.readthedocs.build/en/273/
> Fix uneven blood spreadsheets

- .gitignore
- pypet2bids/poetry.lock
- pypet2bids/pypet2bids/dcm2niix4pet.py
- pypet2bids/pypet2bids/ecat_cli.py
- pypet2bids/pypet2bids/helper_functions.py
- pypet2bids/pyproject.toml
Added logic so that if a .pet2bidsconfig file isn't found (or able to be written) check_pet2bids_config will return whatever value it is able to locate from environment variables. This might just be a new footgun, but it's got the virtue of being new.
Closes issue #291 
----
📚 Documentation preview 📚: https://pet2bids--292.org.readthedocs.build/en/292/
> Changed pypet2bids to check env for vars

- pypet2bids/pypet2bids/ecat_headers.json
Early draft of adding ECAT 7.0 support, initial changes are a simple copy paste of the header/byte fields from version 7.2 into a new entry for version 7.2 in ecat_headers.json.
This pull request will remain a draft until raw ECAT 7.0 data can be acquired to test and evaluate any changes contained within.
> Add Support for ECAT 70

- pypet2bids/poetry.lock
- pypet2bids/pypet2bids/dcm2niix4pet.py
- pypet2bids/pypet2bids/helper_functions.py
- pypet2bids/pyproject.toml
Fixes issue #327 
Doesn't produce output with non-pet (Modality != PT) images, issue #245
----
📚 Documentation preview 📚: https://pet2bids--328.org.readthedocs.build/en/328/
> Bug fixes for Requests not Found; Enhancment for Non-PET modalities

- matlab/ecat2nii.m
Commented lines that write rescaling info to .txt file in .../PET2BIDS/ecat_testing/steps
----
📚 Documentation preview 📚: https://pet2bids--331.org.readthedocs.build/en/331/
> no longer tries to write rescaling factor to .txt file

- contributors.md
- pypet2bids/pypet2bids/ecat.py
This pull request includes a bug fix in the `pypet2bids/ecat.py` file and I added myself to the `contributors.md` file.
I modified the `make_nifti` method to correctly check if the output file name ends with "nii.gz" using `pathlib.Path(output).name` instead of checking the entire path string. Since `pathlib.Path` objects are not iterable, the `"nii.gz" not in output` check would otherwise throw a TypeError, if `output` is not a string but a `Path` object. Since providing the nifti_file as a pathlib.Path object does not throw errors in other places of the code, at least when running `.convert()`, I considered this a bug.
----
📚 Documentation preview 📚: https://pet2bids--333.org.readthedocs.build/en/333/
> Fix bug in make_nifti method to handle Path objects correctly

- .blackignore
- Makefile
- pypet2bids/pypet2bids/dcm2niix4pet.py
- pypet2bids/pyproject.toml
Adds dcm2niix options so user can get up to all kinds of nonsense if required.
All dcm2niix options (barring `-f`) can be modified with:
- the `--dcm2niix-options` flag
- adding them to `~/.pet2bidsconfig` via `PET2BIDS_DCM2NIIX_OPTIONS=`
- or simply exporting them via the same environmental variable `PET2BIDS_DCM2NIIX_OPTIONS` 
----
📚 Documentation preview 📚: https://pet2bids--357.org.readthedocs.build/en/357/
> apply changes requested from PR #353
