- code/ecat_headers.json
Added jsonified version of ecat headers.
> added headers json file

- code/matlab/ecat2nii.m
- code/python/ecat.py
- code/python/ecat2nii.py
Nifti header looks good and the nifti json is a match as well w/ matlab barring the scanner data which can at this time be added via **kwargs when calling the populate_sidecar method from the Ecat class in ecat.py.
> Align nifti header

- pettobids/pettobids/cli.py
- pettobids/pettobids/ecat.py
- pettobids/pettobids/read_ecat.py
- pettobids/pyproject.toml
> added directory table export command to cli

- pypet2bids/pypet2bids/dicom_convert.py
- pypet2bids/pypet2bids/ecat_headers.json
- pypet2bids/pypet2bids/read_ecat.py
Something odd is going on here, created branch to investigate and merge in dicom converter.
> Add dicom converter

- matlab/unit_tests/readECAT7_test.m
Updating readECAT7_test.m in conjunction w/ issue #55
> added documentation to readECAT7_test.m

- pypet2bids/pypet2bids/dcm2niix4pet.py
added method to get TracerRadionuclide from dicom header and then
if gotten to write it out to the nifti sidecar.json
Can still be overridden w/ command line argument or by placing value
in spreadsheet.
> Added write out TracerRadionuclide from dicom to json

- docs/usage.rst
- pypet2bids/pypet2bids/dcm2niix4pet.py
- pypet2bids/pypet2bids/helper_functions.py
- pypet2bids/pyproject.toml
- pypet2bids/tests/test_helper_functions.py
Changes output filename of dcm2niix files to bids paths.
> Path bids id ses extraction

- .gitignore
- pypet2bids/pypet2bids/dcm2niix4pet.py
- pypet2bids/pypet2bids/ecat.py
- pypet2bids/pypet2bids/ecat2nii.py
- pypet2bids/pypet2bids/ecat_cli.py
- pypet2bids/pypet2bids/helper_functions.py
- pypet2bids/pypet2bids/read_ecat.py
- pypet2bids/pyproject.toml
- pypet2bids/tests/test_helper_functions.py
- refactored get_recon_method to helper_functions.py
- refactored tests_helper_functions and test_dcm2niix4pet
- added get_recon_method to ecat conversion
- fixed crash on reading gziped ecat files
- updated .gitignore
- added literal eval to parse_kwargs to avoid capturing non-JS inputs
- bumped version to note minor fixes
> Small fixes:

- pypet2bids/pypet2bids/README.md
Quick fix to readme per @CPernet 's request via issue #145 , closing this PR closes issue.
Feel free to comment or commit suggestions.
> update readme w/ kwargs examples

- .github/workflows/windows.yaml
- docs/usage.rst
- pypet2bids/pypet2bids/README.md
- pypet2bids/pypet2bids/dcm2niix4pet.py
Fixed line endings mess up from previous branch and PR.
> Add Windows Support (Point to install path of dcm2niix)

- .github/workflows/test_phantoms.yaml
- .github/workflows/windows.yaml
Closes #152, gathers phantoms and dependencies on mac, windows, and ubuntu.
> 152 add phantoms to ci

- pypet2bids/pypet2bids/dcm2niix4pet.py
- pypet2bids/tests/test_dcm2niix4pet.py
Fixed checks and units to coincide with updates made to matlab code as this was forked/copied existing matlab functionality.
> fixed to proper units and test values

- .github/workflows/matlab.yaml
- pypet2bids/pypet2bids/helper_functions.py
Just removing a bunch of old stuff from the matlab_ci workflow. This workflow is slightly redundant now that the phantoms workflow exists. However, it makes the badge pass and doesn't really hurt to keep around.
> Fix matlab ci

- pypet2bids/pypet2bids/dcm2niix4pet.py
- pypet2bids/pypet2bids/helper_functions.py
- pypet2bids/tests/test_helper_functions.py
Cleaned up some warning messages if additional kwargs/arguments are supplied. Not happy with this, but can revisit later.
> fix bug #188 with flatten empty series

- paper/codemeta.json
- paper/generate.rb
- paper/persons_info.txt
Generated codemeta.json with script in `paper/generate.rb`.
> generated codemeta.json with orcid's

- .github/workflows/phantoms.yaml
updating dcm2niix to v1.0.20230411 in CI
> update dcm2niix version in CI

- paper.md
Just updated my name and affiliations, and made a few small suggestions in the text.
> Several small suggestions

- pypet2bids/pypet2bids/dcm2niix4pet.py
- pypet2bids/pyproject.toml
----
📚 Documentation preview 📚: https://pet2bids--258.org.readthedocs.build/en/258/
> added entrypoint for updating a json from a pet dicom file

- .readthedocs.yaml
- Makefile
- docs/conf.py
- docs/index.rst
- docs/installation.rst
- docs/matlab.rst
- docs/modules.rst
- docs/pypet2bids.rst
- matlab/get_pet_metadata.m
- pypet2bids/poetry.lock
- pypet2bids/pypet2bids/dcm2niix4pet.py
- pypet2bids/pypet2bids/helper_functions.py
- pypet2bids/pypet2bids/sidecar.py
- pypet2bids/pyproject.toml
----
📚 Documentation preview 📚: https://pet2bids--257.org.readthedocs.build/en/257/
> fix-rtd-formatting

- .gitignore
- Makefile
- docs/spreadsheets.rst
- docs/usage.rst
- pypet2bids/pypet2bids/ecat.py
- pypet2bids/tests/test_dcm2niix4pet.py
- pypet2bids/tests/test_library_command_line_interfaces.py
----
📚 Documentation preview 📚: https://pet2bids--261.org.readthedocs.build/en/261/
> Add Instructions for Users to Run Tests & Add Easily Retrievable Test Data

- pypet2bids/pypet2bids/dcm2niix4pet.py
- pypet2bids/pypet2bids/helper_functions.py
- pypet2bids/pyproject.toml
Pretty trivial fix for issue #267
----
📚 Documentation preview 📚: https://pet2bids--269.org.readthedocs.build/en/269/
> very small fix for tsv spreadsheets

- pypet2bids/pypet2bids/ecat_header_update.py
- pypet2bids/pypet2bids/write_ecat.py
- pypet2bids/pyproject.toml
closes issue #264 
----
📚 Documentation preview 📚: https://pet2bids--270.org.readthedocs.build/en/270/
> added small script to update ecat mainheader with, bump version

- pypet2bids/pypet2bids/dcm2niix4pet.py
- pypet2bids/pypet2bids/ecat.py
- pypet2bids/pypet2bids/helper_functions.py
- pypet2bids/pypet2bids/update_json_pet_file.py
- pypet2bids/pyproject.toml
@dlevitas update for ezBIDs
----
📚 Documentation preview 📚: https://pet2bids--275.org.readthedocs.build/en/275/
> Create unique series description

- pypet2bids/pypet2bids/dcm2niix4pet.py
- pypet2bids/pypet2bids/ecat.py
- pypet2bids/pypet2bids/helper_functions.py
- pypet2bids/pyproject.toml
----
📚 Documentation preview 📚: https://pet2bids--279.org.readthedocs.build/en/279/
> Update SeriesDescription to use ProctocolName as primary field

- Makefile
- README.md
- docs/pypet2bids.rst
- docs/usage.rst
- pypet2bids/README.md
- pypet2bids/pypet2bids/convert_pmod_to_blood.py
- pypet2bids/pypet2bids/dcm2niix4pet.py
- pypet2bids/pypet2bids/dicom_convert.py
- pypet2bids/pypet2bids/ecat_cli.py
- pypet2bids/pypet2bids/ecat_header_update.py
- pypet2bids/pypet2bids/golden_ecat.py
- pypet2bids/pypet2bids/helper_functions.py
- pypet2bids/pypet2bids/is_pet.py
- pypet2bids/pypet2bids/metadata_spreadsheet_example_reader.py
- pypet2bids/pypet2bids/multiple_spreadsheets.py
- pypet2bids/pypet2bids/single_spreadsheet.py
- pypet2bids/pypet2bids/update_json_pet_file.py
- pypet2bids/pyproject.toml
- pypet2bids/tests/test_thisbytes.py
closes #276  pending approval from @nbeliy
----
📚 Documentation preview 📚: https://pet2bids--284.org.readthedocs.build/en/284/
> 276 joss review documentation review

- .github/workflows/phantoms.yaml
- pypet2bids/poetry.lock
- pypet2bids/pypet2bids/ecat.py
- pypet2bids/pypet2bids/helper_functions.py
- scripts/python_conversions.sh
- Fixes typo in ecat.py for radiopharmaceutical
- Correctly sets other times relative to timezeros for ECAT's 
----
📚 Documentation preview 📚: https://pet2bids--295.org.readthedocs.build/en/295/
> Fixes for issues 293 and 288

- pypet2bids/poetry.lock
update lock file
----
📚 Documentation preview 📚: https://pet2bids--302.org.readthedocs.build/en/302/
> update lock file

- JOSS_metadata/persons_info.txt
- pypet2bids/pyproject.toml
----
📚 Documentation preview 📚: https://pet2bids--305.org.readthedocs.build/en/305/
> tag and update contributor list

- .github/workflows/phantoms.yaml
- scripts/matlab_conversions.m
- scripts/python_conversions.sh
Fixes issues w/ phantoms scripts attempting to convert phantoms that aren't there.
----
📚 Documentation preview 📚: https://pet2bids--312.org.readthedocs.build/en/312/
> Fix phantoms ci

- paper.md
This should match authors and affiliations to Zenodo archive. Can you please double check, also against the archive? I will also look a the rendered paper again once it's up.
This PR is connected to the JOSS reviewing process over at https://github.com/openjournals/joss-reviews/issues/6067
> Affiliations and authors

- docs/spreadsheets.rst
- spreadsheet_conversion/Readme.md
The links on the README don't work here. So I've updated them so they download the right files.
----
📚 Documentation preview 📚: https://pet2bids--324.org.readthedocs.build/en/324/
> Updated links for spreadsheet conversion

- pypet2bids/poetry.lock
- pypet2bids/pypet2bids/helper_functions.py
- pypet2bids/pypet2bids/metadata_spreadsheet_example_reader.py
- pypet2bids/pypet2bids/update_json_pet_file.py
- pypet2bids/pyproject.toml
introduced error by attempting to read json file that's no longer there.
----
📚 Documentation preview 📚: https://pet2bids--338.org.readthedocs.build/en/338/
> removed errant use of metadata.json file instead of import

- .github/workflows/phantoms.yaml
- .github/workflows/python.yaml
----
📚 Documentation preview 📚: https://pet2bids--344.org.readthedocs.build/en/344/
> update ubuntu on phantom workflow
